<a href="https://colab.research.google.com/github/rajkonkret/analiza_danych_9_09_2026/blob/main/analiza_danych_9_09_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Rozpoczęcie pracy <br>
**strong**
**pogrubiony tekst**\
*kursywa*

[tekst linku](naukapythona.pl)

język markdown:
# Nowa sekcja

In [ ]:
1 + 2

3

#początek pracy  z pythonem
## sekcja1

In [ ]:
print("Radek")  # wypisz/wydrukuj

Radek


https://peps.python.org/pep-0008/

11:15

In [ ]:
# zmienna
liczba_calkowita = 42 # int - liczba całkowita

In [ ]:
liczba_calkowita

42

In [ ]:
print(liczba_calkowita)

42


In [ ]:
import sys

In [ ]:
print(sys.int_info)

sys.int_info(bits_per_digit=30, sizeof_digit=4, default_max_str_digits=4300, str_digits_check_threshold=640)


In [ ]:
cena = 19.9999 # float - liczba zmiennoprzeinkowa - problem zaokraglenia

In [ ]:
cena

19.9999

In [ ]:
print(0.1 + 0.9)

1.0


In [ ]:
print (0.1 + 0.2)

0.30000000000000004


In [ ]:
print(0.1 + 0.7)

0.7999999999999999


decimal - pozwala bezpieczniej działac z liczbami zmiennoprzeinkowymi

In [ ]:
import decimal

a = decimal.Decimal("3.45")
print(a)

3.45


In [ ]:
nazwa1 = "czujnik 1"
nazwa2 = 'czujnik 2'

In [ ]:
print(nazwa1)

czujnik 1


In [ ]:
print(nazwa2)

czujnik 2


In [ ]:
aktywny = True # bool - wartość logiczna (True/False)

In [ ]:
print(aktywny)

True


In [ ]:
print(f"Cena po zaokrągleniu: {cena:.2f} zł")  # f-string jako formatowanie drukowania

Cena po zaokrągleniu: 20.00 zł


In [ ]:
cena = round(cena, 2)
print(cena)

20.0


In [ ]:
liczba = "123"

In [ ]:
print(liczba  + 1)

TypeError: can only concatenate str (not "int") to str

In [ ]:
print(liczba + "1")  # konkatenacja, łaczennie stringu

In [ ]:
print(int(liczba) + 1)  # rzutownie (casting)

In [ ]:
# float, str
liczba_cal = 5.9
nowa_liczba_cal = int(liczba_cal)
print(nowa_liczba_cal)

In [ ]:
print(5 * "34")

# Kolekcje
## słownik, lista, zbiór, krotka (tuple)

In [ ]:
# lista - zachowuje kolejność
chaotyczna_lista = ['Tomek', 12, 45.6777, True, nowa_liczba_cal]
print(chaotyczna_lista)

['Tomek', 12, 45.6777, True, 5]


In [ ]:
liczby = [43, 546, 324, 65, 12, 76, 3, 2345, 456, 788]  # 0,1,2,3,4

In [ ]:
liczby

[43, 546, 324, 65, 12, 76, 3, 2345, 456, 788]

In [ ]:
print(liczby[0])

43


In [ ]:
print(liczby[len(liczby) - 1])

788


In [ ]:
print(liczby[-1]) # ostatni element z kolekcji

788


In [ ]:
# slicing - fragment listy
print(chaotyczna_lista[1:3]) # indeksy 1 i 2, niewłącznie

['Radek', 'Radek']


In [ ]:
# od indeksu 2 do 8 włacznie
print(liczby[2:9])

[324, 65, 12, 76, 3, 2345, 456]


In [ ]:
print(liczby[0:3])

[43, 546, 324]


In [ ]:
print(liczby[:3])

[43, 546, 324]


In [ ]:
print(liczby[2:]) # z ostatnim włacznie

[324, 65, 12, 76, 3, 2345, 456, 788]


In [ ]:
print(len(liczby))

10


In [ ]:
print(liczby[2:9])  # niewłacznie

[324, 65, 12, 76, 3, 2345, 456]


In [ ]:
print(liczby[10])

IndexError: list index out of range

In [ ]:
print(liczby[10:30])  # pusta lista

[]


In [ ]:
chaotyczna_lista.append("lunch")
print(chaotyczna_lista)

['Tomek', 12, 45.6777, True, 5, 'lunch']


In [ ]:
chaotyczna_lista.insert(2, "Radek")  # na indeksie 2
print(chaotyczna_lista)

['Tomek', 12, 'Radek', 45.6777, True, 5, 'lunch']


In [ ]:
chaotyczna_lista[0] = "Przerwa"
print(chaotyczna_lista)

['Przerwa', 12, 'Radek', 45.6777, True, 5, 'lunch']


In [ ]:
chaotyczna_lista.remove(12)
print(chaotyczna_lista)

['Przerwa', 'Radek', 45.6777, True, 5, 'lunch']


In [ ]:
# usunięcie po indeksie
print(chaotyczna_lista.pop(3))

True


In [ ]:
liczby.sort(reverse=True)
print(liczby)

[2345, 788, 546, 456, 324, 76, 65, 43, 12, 3]


In [ ]:
# posortowac chaotyczna lista
chaotyczna_lista.sort()

TypeError: '<' not supported between instances of 'float' and 'str'

In [ ]:
# list comprehensions tansze i szybsze
mnoznik = [liczba * 2 for liczba in liczby]
print(mnoznik)

mnoznik_loop = [] # pusta lista
for liczba in liczby: # wykona 10 razy
    mnoznik_loop.append(liczba * 2)
print("Wyszlismy z pętli")   # pojawi się 1 raz

[4690, 1576, 1092, 912, 648, 152, 130, 86, 24, 6]
Wyszlismy z pętli


In [ ]:
print(type(mnoznik))

<class 'list'>


In [ ]:
print(mnoznik_loop)

[4690, 1576, 1092, 912, 648, 152, 130, 86, 24, 6]


 set - zbiór \
przechowuje unikalne wartości
nie zachowuje kolejności, nie ma indeksu

In [ ]:
lista = [23, 23, 45, 67, 89, 0, 23, 34]
lista.sort(reverse=True)
print(lista)

[89, 67, 45, 34, 23, 23, 23, 0]


In [ ]:
# usunąc 23
lista.remove(23)
print(lista)


[89, 67, 45, 34, 23, 23, 0]


In [ ]:
zbior = set(lista)
print(zbior)

{0, 34, 67, 45, 23, 89}


In [ ]:
pusty_zbior = set()  # tylko i wyłącznie za pomocą słowka
print(pusty_zbior)
print(type(pusty_zbior))

set()
<class 'set'>


In [ ]:
klient = {1024, "Kielce", 7, 7}
print(klient)

{1024, 'Kielce', 7}


słownik \
para {"klucz":"wartosc"}


In [ ]:
pusty_slownik = {}
print(type(pusty_slownik))
print(pusty_slownik)

<class 'dict'>
{}


In [ ]:
klient_slownik = {"miasto": ["Łódź", "Warszawa", "Kraków", "Rzeszów", "Siedlce"]}

In [ ]:
print(klient_slownik)

{'miasto': ['Łódź', 'Warszawa', 'Kraków', 'Rzeszów', 'Siedlce']}


In [ ]:
slownik_user = {"id": 1024, "miasto": "Kielce", 'Ilosc': 7}
print(slownik_user['miasto'])

Kielce


In [ ]:
# kolekcje haszowane
# znaczząco szybsze przy wyszukiwaniu
print(1024 in klient)  # sprawdzenie czy 1024 istnieje w klient

True


In [ ]:
slownik_user["id"]= 2345
print(slownik_user)

{'id': 2345, 'miasto': 'Kielce', 'Ilosc': 7}


In [ ]:
print(slownik_user['data'])

KeyError: 'data'

In [ ]:
print(slownik_user.get("data"))

None


In [ ]:
# None - odpowiednik null, brak wartosc, wartosc nieokreslona

In [ ]:
# zrobic słownik
# ma miec min 3 klucze
# jeden klucz ma miec float, int
# drugi: lista
# trzeci słownik (dwa klucze)
# powypisywac wybrane wartosci
# del lista - usnięcie z pamięci zmiennnej

In [131]:
dane = {
  "id": 1024,
  "miasta": ["Kielce", "Warszawa", "Kraków"],
  "Ilosc": {"zakupy": 543, "wydatki": 321}
}
print(dane["miasta"][1])
print(dane["Ilosc"]["zakupy"])

Warszawa
543


In [133]:
lista = [1, 2, 3, 7, 1, 2, 8, 9, 0, 10]

In [134]:
print(dict.fromkeys(lista))

{1: None, 2: None, 3: None, 7: None, 8: None, 9: None, 0: None, 10: None}


In [135]:
print(list(dict.fromkeys(lista)))  # zachowa kolejność

[1, 2, 3, 7, 8, 9, 0, 10]


In [138]:
slownik1 = {"id":1, "user": "Tom"}
slownik2 = {"student" : slownik1}


In [139]:
print(slownik2)

{'student': {'id': 1, 'user': 'Tom'}}


Krotka - Tuple\
kolekcja niemutowalna

In [140]:
miasta = ("Kielce", "Warszawa", "Kraków")
print(miasta)

('Kielce', 'Warszawa', 'Kraków')


pętla while

In [141]:
lista = [1, 2, 3, 7, 1, 2, 8, 9, 0, 10]

In [142]:
while 1 in lista: # pętla sterowana warunkiem
    lista.remove(1)

print(lista)

[2, 3, 7, 2, 8, 9, 0, 10]


instrukcja warunkowa

In [144]:
temperatura = 7.5

if temperatura > 30:
    status = "upał"
elif temperatura > 20:
    status = "ciepło"
else:
    status = "chłodno"

print(status)

chłodno


In [145]:
# od pythona 3.10 match case

dane = "python"

match dane:
    case "python":
        print("Znam pythona")
    case "java":
        print("Jave też znam")
    case _:
        print("Nie znam")

Znam pythona


In [146]:
print(temperatura == 8)  # porównanie

False


funkcje

In [147]:
def przedstaw_sie():
    return "Cześć"  # zwraca wartość

In [148]:
def dodaj_dwa(liczba):
    return liczba + 2

In [150]:
def nowa_lista(*args):
    lista_1 = []
    lista_1.append(args)
    return lista_1

In [151]:
print(przedstaw_sie())

Cześć


In [152]:
print(dodaj_dwa(15))
print(dodaj_dwa(35))
print(dodaj_dwa(70))

17
37
72


In [153]:
print(nowa_lista())

[()]


In [154]:
print(nowa_lista(4,5,6,7))

[(4, 5, 6, 7)]


In [159]:
def nowa_lista2(*args):
    lista_2 = []
    lista_2.extend(args)
    return lista_2

In [160]:
print(nowa_lista2(4,5))

[4, 5]


funkcja lambda

In [161]:
def dodaj(a, b):
    return a + b

In [162]:
print(dodaj(2, 3))

5


In [163]:
dodaj_2 = lambda a, b: a + b

In [164]:
print(dodaj_2(2, 3))

5


In [165]:
lista = [2, 3, 7, 2, 8, 9, 0, 10]  # przemnożyc przez 2

In [166]:
# map() - funkcja wyzszego rzędu, jako argument przyjmuje inna funkcję
# lambda jako funkcja anonimowa
print(list(map(lambda a: a * 2, lista)))


[4, 6, 14, 4, 16, 18, 0, 20]


In [ ]:
# filter(), reduce()

Klasa - przepis, szablon, stempel \
obiekt - zbudowany wg klasy, odcisk stempla, przysłowiowe ciasto

In [190]:
class User:
    """Komentarz - dokumentacja"""

    def __init__(self, name, id):
        """Metoda inicjalizująca (konstruktor)"""
        self.name = name
        self.id = id

    def powitanie(self):
        print("Nazywam się:", self.name)

    def __str__(self):
        return f"{self.name} {self.id}"

In [ ]:
# pydoc

In [191]:
# cz1 = User()
cz1 = User("Radek", 1)

In [192]:
print(cz1)  # <__main__.User object at 0x7f9143686f90>, pododaniu __str__ Radek 1

Radek 1


In [178]:
print(cz1.name)

Radek


In [179]:
cz1.powitanie()

Nazywam się: Radek


# Numpy
Fast and versatile, the NumPy vectorization, indexing, and broadcasting\
concepts are the de-facto standards of array computing today.

In [195]:
!pip install numpy

In [196]:
import numpy as np

In [197]:
liczby = [43, 546, 324, 65, 12, 76, 3, 2345, 456, 788]  # 0,1,2,3,4

In [198]:
tablica_1 = np.array(liczby)  # tworzenie tablicy z listy

In [199]:
tablica_1

array([  43,  546,  324,   65,   12,   76,    3, 2345,  456,  788])

In [200]:
print(tablica_1)

[  43  546  324   65   12   76    3 2345  456  788]


In [201]:
# przemnożyc razy 2 wszystkie elementy tablicy

# broadcasting - wykonanie operacji dla każdego elementu tablicy
print(tablica_1 * 2)

[  86 1092  648  130   24  152    6 4690  912 1576]


In [202]:
zera = np.zeros(5)  # np.float
print(zera)

[0. 0. 0. 0. 0.]


In [203]:
zera

array([0., 0., 0., 0., 0.])

In [204]:
zera2d = np.zeros((4,5)) # (wiersze,kolumny)
print(zera2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [205]:
print(type(zera2d))

<class 'numpy.ndarray'>


In [206]:
print(zera.dtype)

float64


In [207]:
print(zera2d.shape)

(4, 5)


In [208]:
zera_int = np.zeros(5, dtype=int)
print(zera_int)
print(zera_int.dtype)

[0 0 0 0 0]
int64


In [209]:
zera_int = np.zeros(5, dtype=np.int64)
print(zera_int)
print(zera_int.dtype)

[0 0 0 0 0]
int64


In [210]:
jedynki = np.ones(5)
print(jedynki)
print(jedynki.dtype)

[1. 1. 1. 1. 1.]
float64


In [211]:
print(jedynki.shape)

(5,)


In [214]:
krotka_1 = (5,)
print(type(krotka_1))

<class 'tuple'>


In [2]:
import numpy as np

In [3]:
zakres = np.arange(1, 11)
print(zakres)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
tablica2d = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(tablica2d)

[[1 2 3]
 [4 5 6]]


In [5]:
print(tablica2d[1, 2]) # drugi wiersz, trecia kolumna

6


In [6]:
losowe = np.random.random(5)
print(losowe)

[0.0539575  0.6238053  0.10387646 0.21551329 0.07496843]


In [7]:
losowe_int = np.random.randint(1, 50, 5)
print(losowe_int)

[ 1 27 38 44 26]


In [8]:
# statystyki
print(np.mean(losowe_int))

27.2


In [9]:
print(np.median(losowe_int))

27.0


In [10]:
print(np.std(losowe_int))

14.74313399518569


In [11]:
print(np.min(losowe_int))
print(np.max(losowe_int))

1
44


In [13]:
print(losowe_int[losowe_int > 25])  # maska, filtrowanie

[27 38 44 26]


Przykład analizy

In [14]:
sprzedaz = np.array([120, 135, 98, 150, 180, 110, 95, 210,170,140])
print(sprzedaz)

[120 135  98 150 180 110  95 210 170 140]


In [15]:
# wypisac podstawowe miary
print("Średnia:", np.mean(sprzedaz))

Średnia: 140.8


In [16]:
print("Mediana:", np.median(sprzedaz))
print("Minimum:", np.min(sprzedaz))
print("Maksimum:", np.max(sprzedaz))
print("Odchylenie:", np.std(sprzedaz))
print("Suma:", np.sum(sprzedaz))

Mediana: 137.5
Minimum: 95
Maksimum: 210
Odchylenie: 35.50718237202158
Suma: 1408


In [17]:
# duza sprzedaz - większa od średniej
duza_sprzedaz = sprzedaz[sprzedaz > np.mean(sprzedaz)]
print(duza_sprzedaz)

[150 180 210 170]


In [19]:
# ile razy była duza sprzedaz
dni_duzej_sprzedazy = len(duza_sprzedaz)
print(dni_duzej_sprzedazy)

4


In [20]:
wzrost_sprzedazy = sprzedaz * 1.10
print(wzrost_sprzedazy)

[132.  148.5 107.8 165.  198.  121.  104.5 231.  187.  154. ]


In [21]:
# 3 sklepy, 4 miesiace

sprzedaz = np.array(
    [
        [120, 130, 140, 150],
        [100, 110, 115, 125],
        [200, 190,210, 220]
    ]
)

print(sprzedaz)


[[120 130 140 150]
 [100 110 115 125]
 [200 190 210 220]]


In [ ]:
# oblicz:
# suma dla kazdego sklepu
# suma dla kazdego miesiąca
# najlepszy sklep

In [23]:
suma_sklep = sprzedaz[0].sum()
print(suma_sklep)

540


In [24]:
print(np.sum(sprzedaz[0]))

540


In [25]:
suma_sklepy_wiersze = sprzedaz.sum(axis=1) # per sklep
print("Suma dla każdego sklepu:", suma_sklepy_wiersze)

Suma dla każdego sklepu: [540 450 820]


In [26]:
suma_miesiacce_kolumna = sprzedaz.sum(axis=0)
print("Suma dla każdego miesiąca:", suma_miesiacce_kolumna)

Suma dla każdego miesiąca: [420 430 465 495]


In [28]:
# najlpeszy sklep
print(np.max(suma_sklepy_wiersze))

820


In [30]:
najlepszy_sklep = np.argmax(suma_sklepy_wiersze)
print("Najlepszy sklep:", najlepszy_sklep  + 1)

Najlepszy sklep: 3


statystyka bez numpy

In [31]:
import statistics as st

pensje = [5000, 5500, 6000, 30000]

print(st.mean(pensje))
print(st.median(pensje))
print(st.mode(pensje))  # dominanta

11625
5750.0
5000


In [ ]:
# lista w liscie
# zrobic tablice numpy
# wypisac kształt

In [32]:
lista = [[5,6], [7,8]]
b = np.array(lista)
print(b)

[[5 6]
 [7 8]]


In [33]:
print(b.shape)

(2, 2)


In [34]:
# ravel() - spłaszczenie
print(b.ravel())

[5 6 7 8]


In [35]:
print(b)  # oryginał bez zmian

[[5 6]
 [7 8]]


In [36]:
# reshape() - zmiana kształtu
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
new_arr = arr.reshape(4, 3)
new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
new_err_arr = arr.reshape(3, 5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [39]:
print(new_arr.transpose())

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [40]:
arr10 = np.arange(1, 10).reshape(3, 3)
arr10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr_split = np.split(arr10, 3)
print(arr_split)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [42]:
arr_hsplit =np.hsplit(arr10, 3)
print(arr_hsplit)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [43]:
arr11 = np.arange(1, 10).reshape(3, 3)
print(arr11.dtype) # dane typu integer - cłakowite

int64


In [44]:
# konwersja na inny typ
arr12 = arr11.astype(float)
print("Zmieniamy typ na:", arr12.dtype) # zmiennoprzecinkowy

Zmieniamy typ na: float64


In [45]:
# zamiana danych na typ pythonowy
list1 = arr11.tolist()
print("Lista pythonowa:", list1)
print("typ listy:", type(list1))

Lista pythonowa: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
typ listy: <class 'list'>


In [46]:
arr_even = np.arange(0, 10 , 2)
print(arr_even)

[0 2 4 6 8]
